export {main as alert} from './alert'
export {main as archive} from './archive'
export {main as cancel} from './cancel'
export {main as close} from './close'
// export {main as create} from './create'
// export {main as delete} from './delete'
// export {main as faq} from './faq'
// export {main as open} from './open'
// export {main as option} from './option'
// export {main as region} from './region'